### ISSUE TITLE
[Clarification] Android status

### ISSUE THREAD

**Issue by Serdnad** [jonataslaw/VideoCompress#1]
Hi, thanks for sharing this library! I noticed that the README says "TODO: Finish methods on android". Does this mean some features available to iOS aren't currently implemented on Android, and if so, which ones?

**Comment by jonataslaw** [comment]
> Hi, thanks for sharing this library! I noticed that the README says "TODO: Finish methods on android". Does this mean some features available to iOS aren't currently implemented on Android, and if so, which ones?

Crop video, and tracking progress is not yet implemented on android.
I already got it ready, for that, in less than 30 minutes of work I put it all to work. I made this library in a hurry to finish a job that had video compression as a requirement before uploading to the server, and due to the advanced time and absence of these resources, I ended up uploading the repository before finishing, but I'll probably finish this in the next end week.
I intend to include GL video effects, and other functions to make it a powerful video editor (since using ffmpeg, which is the fastest way is not a solution due to processing time and patent problems, and GPL, which make commercial apps and upload to applestore impossible), but I don't know yet if I do this in this lib or create another one for this more extended process.
