### ISSUE TITLE
Slow compression 

### ISSUE THREAD

**Issue by arashbi** [jonataslaw/VideoCompress#99]
I was looking for a faster way of compressing the videos. But it seems it is almost as slow as FFMpeg, based on measurement I did on the example application. 
To convert a 1 minute video, the time is around 40s

**Comment by jonataslaw** [comment]
The compression speed depends on the device, and there is no chance that you can achieve a faster compression, this package uses the native codecs to do this. FFMPEG and anything else will need to decode and then convert. However, there is no way to do magic, the speed depends on the device. I tested it on my two devices and on both the conversation took less than 3 seconds for a 43 second video.

**Comment by jonataslaw** [comment]
Just an addendum, compression is fast for videos made on the device, or original videos, if you pass the video through a program, that program may corrupt or decode that file incorrectly, which will cause a slower compression.
There are several reasons, but in this case it is not the package that is responsible for this.

**Comment by arashbi** [comment]
How about telegram? Manages to compress videos in a much faster way.

**Comment by amosogra** [comment]
All these things need the right compression algorithm, otherwise this package should be named something else, maybe updown_sampler... because that is what it does. checkout Video Panda on Google Play store. Now that is a true Video Compression algorithm in play. You can test with the same video and find out that while Video Panda compresses, this package sometimes increases the size more than the input video. Sad!

**Comment by llli0v0** [comment]
@amosogra We should go easy on open source authors, who are doing this work for free. Open source projects will continue to improve, maybe there will be a better solution in the future.😊😊😊
